/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MdxPublicRouteImport } from './routes/mdxPublic'
import { Route as CombinedMdxRouteImport } from './routes/combined-mdx'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPublicLessonsRouteImport } from './routes/_authenticated/public-lessons'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMdxRouteImport } from './routes/_authenticated/mdx'
import { Route as AuthenticatedLessonPlanRouteImport } from './routes/_authenticated/lesson-plan'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const MdxPublicRoute = MdxPublicRouteImport.update({
  id: '/mdxPublic',
  path: '/mdxPublic',
  getParentRoute: () => rootRouteImport,
} as any)
const CombinedMdxRoute = CombinedMdxRouteImport.update({
  id: '/combined-mdx',
  path: '/combined-mdx',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPublicLessonsRoute =
  AuthenticatedPublicLessonsRouteImport.update({
    id: '/public-lessons',
    path: '/public-lessons',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMdxRoute = AuthenticatedMdxRouteImport.update({
  id: '/mdx',
  path: '/mdx',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLessonPlanRoute = AuthenticatedLessonPlanRouteImport.update({
  id: '/lesson-plan',
  path: '/lesson-plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/combined-mdx': typeof CombinedMdxRoute
  '/mdxPublic': typeof MdxPublicRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lesson-plan': typeof AuthenticatedLessonPlanRoute
  '/mdx': typeof AuthenticatedMdxRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/public-lessons': typeof AuthenticatedPublicLessonsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/combined-mdx': typeof CombinedMdxRoute
  '/mdxPublic': typeof MdxPublicRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/lesson-plan': typeof AuthenticatedLessonPlanRoute
  '/mdx': typeof AuthenticatedMdxRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/public-lessons': typeof AuthenticatedPublicLessonsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/combined-mdx': typeof CombinedMdxRoute
  '/mdxPublic': typeof MdxPublicRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/lesson-plan': typeof AuthenticatedLessonPlanRoute
  '/_authenticated/mdx': typeof AuthenticatedMdxRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/public-lessons': typeof AuthenticatedPublicLessonsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/combined-mdx'
    | '/mdxPublic'
    | '/dashboard'
    | '/lesson-plan'
    | '/mdx'
    | '/profile'
    | '/public-lessons'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/combined-mdx'
    | '/mdxPublic'
    | '/dashboard'
    | '/lesson-plan'
    | '/mdx'
    | '/profile'
    | '/public-lessons'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/combined-mdx'
    | '/mdxPublic'
    | '/_authenticated/dashboard'
    | '/_authenticated/lesson-plan'
    | '/_authenticated/mdx'
    | '/_authenticated/profile'
    | '/_authenticated/public-lessons'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CombinedMdxRoute: typeof CombinedMdxRoute
  MdxPublicRoute: typeof MdxPublicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mdxPublic': {
      id: '/mdxPublic'
      path: '/mdxPublic'
      fullPath: '/mdxPublic'
      preLoaderRoute: typeof MdxPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combined-mdx': {
      id: '/combined-mdx'
      path: '/combined-mdx'
      fullPath: '/combined-mdx'
      preLoaderRoute: typeof CombinedMdxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/public-lessons': {
      id: '/_authenticated/public-lessons'
      path: '/public-lessons'
      fullPath: '/public-lessons'
      preLoaderRoute: typeof AuthenticatedPublicLessonsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mdx': {
      id: '/_authenticated/mdx'
      path: '/mdx'
      fullPath: '/mdx'
      preLoaderRoute: typeof AuthenticatedMdxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lesson-plan': {
      id: '/_authenticated/lesson-plan'
      path: '/lesson-plan'
      fullPath: '/lesson-plan'
      preLoaderRoute: typeof AuthenticatedLessonPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLessonPlanRoute: typeof AuthenticatedLessonPlanRoute
  AuthenticatedMdxRoute: typeof AuthenticatedMdxRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPublicLessonsRoute: typeof AuthenticatedPublicLessonsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLessonPlanRoute: AuthenticatedLessonPlanRoute,
  AuthenticatedMdxRoute: AuthenticatedMdxRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPublicLessonsRoute: AuthenticatedPublicLessonsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CombinedMdxRoute: CombinedMdxRoute,
  MdxPublicRoute: MdxPublicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
